adapters/filesManager.go, config/config.go, config/configModels.go, config/rawService.go, productImport/ontologyRead/rulesHandler.go, productImport/productImportHandler.go, service.default.yaml
Offers import should work with folder structure
- source folder for incoming file
- in progress - folder for in_progress file
- report-for report
User should know which folders are for products import, wich-for offers, so folders should be splited for import
=> TSAPPS-178 Configs for new import handler

install.sh
install.sh updated for using new user flow with offers
=> TSAPPS-187 update install.sh

di/di.go, externalAPI/rest/rest.go, externalAPI/rest/rest_test.go, externalAPI/tradeshiftAPI/supplierAPI.go, externalAPI/tradeshiftAPI/supplierAPI_test.go, main.go, offerImport/importHandler/importOffersInterface.go, offerImport/importHandler/importOffersToTradeshift.go, offerImport/offerImportHandler.go, offerImport/offerReader/rawHeader.go
Offer import starts before product import.
Offer import handler upload file with offers and move it to "processed" folder. Then uploaded offers are processed to tradeshift
+ fixed bug in createOffer request
=> TSAPPS-181 Handler for offers import

adapters/adapterInterface.go, adapters/csvH/adapter.go, adapters/excelH/adapter.go, adapters/handler.go, adapters/txtH/adapter.go, file/converter.go, file/csvFile/csv.go, file/txtFile/txt.go, file/xlsxFile/xlsx.go, file/xlsxFile/xlsx_test.go, utils/stringUtils.go, utils/stringUtils_test.go, utils/utils.go, utils/utils_test.go
Tool should support input XLXS files
Definite file sheets should be converted to csv file as simple list of rows and proceeded by existened handlers
=> TSAPPS-200 Reading XLSX files

offerImport/offerImportHandler.go, offerImport/offerReader/offerReader.go
Failed Offer import should not block product import
=> TSAPPS-193 [hotfix] Fix bug

config/rawService.go
PORT should not be requirement parameter while tool is not service
=> TSAPPS-225 Fix requirement param

productImport/mapping/handlerInterface.go, productImport/mapping/mapping.go, productImport/mapping/mapping_test.go, productImport/productImportHandler.go, productImport/reports/reportsHandler.go, productImport/reports/reportsHandler_test.go
ProductImport report use hardcoded columns. It breaks Validation 2 scenario when custom mapping is defined
=> TSAPPS-220 [hotfix] Build productImport report with columns from mapping

productImport/reports/reportsHandler.go
In report's attribute list category is optional attribute.
In this case it should be taken category of product from source product data
Add some comments and renamings to clearify legacy
=> TSAPPS-222 [hotfix] Define category from source product info

externalAPI/rest/rest.go, externalAPI/rest/restClientInterface.go, externalAPI/tradeshiftAPI/supplierAPI.go, offerImport/importHandler/importOffersToTradeshift.go, offerImport/offerImportHandler.go, offerImport/offerReader/offerReader.go
For new offer should be used unrequired fields from uploaded file: Valid From, Expires At, Countries
This params can be added to Offer via API PUT method
=> TSAPPS-207 Aditional parameters for offer creation

adapters/csvH/adapter.go, adapters/csvH/adapter_test.go, offerImport/importHandler/importOffersToTradeshift.go, productImport/ontologyValidator/reportValidator.go, productImport/reports/successReportBuilder.go, utils/sliceUtils.go, utils/utils.go
Tradeshift xlsx file has 2 first formatted rows. To select valid header this rows should be skipped
It was implemented on CSV read level
=> TSAPPS-213 Skip template header and empty rows

productImport/ontologyValidator/reportValidator.go, productImport/ontologyValidator/validator.go, productImport/product/productHandler.go, productImport/product/productHandlerInterface.go, productImport/product/productModels.go, productImport/reports/successReportBuilder.go
In attributes validation (Validation-2) use product's category, if attribute's category is empty
=> TSAPPS-223 Use category from product in Validation-2

file/converter.go, file/converter_test.go, file/xlsxFile/xlsx.go, prepareImport/prepareImportHandler.go, prepareImport/xlsxSheetToCSVConverter.go, prepareImport/xlsxSheetToCSVConverterInterface.go
Optional sheet Price should be converted to importable csv file
That means, it should not have empty columns or rows. Service header lines also should be skipped
=> TSAPPS-239 Convert OfferItemsData from xlsx sheet to csv

config/configModels.go, config/rawService.go, di/di.go, externalAPI/tradeshiftAPI/supplierAPI.go, file/converter.go, file/converter_test.go, offerItemImport/offerITemImportHandler.go, offerItemImport/offerItemHandlerInterface.go, outwardImport/importToTradeshift/importProductsAndOffers.go, outwardImport/importToTradeshift/importReport.go, outwardImport/importToTradeshift/importToTradeshiftHandler.go, outwardImport/outwardImportInterface.go, productImport/productImportHandler.go, productImport/tradeshiftImportHandler/importProductsHandler.go, service.default.yaml
For offerItems should be used same import to tradeshift as for products. Same folders and same report
Also import requires configurable locale and currency for supplier.
=> TSAPPS-242 Add import to Tradeshift for offer items

externalAPI/tradeshiftAPI/supplierAPI.go, offerItemImport/offerITemImportHandler.go, outwardImport/importToTradeshift/importProductsAndOffers.go, outwardImport/outwardImportInterface.go, productImport/tradeshiftImportHandler/importProductsHandler.go
OfferITems import required param "shareOffers=true" in url
=> TSAPPS-250 Fix bug

install.sh
=> TSAPPS-240_modify_install

offerItemImport/offerItemMapping/offerItemMappingHandler.go, offerItemImport/offerItemMapping/offerItemMappingHandler_test.go, productImport/mapping/handlerInterface.go, productImport/mapping/mapping.go, productImport/mapping/mappingModel.go, productImport/mapping/mapping_test.go, productImport/ontologyValidator/validator.go, productImport/product/productHandler.go, productImport/product/productHandlerInterface.go, productImport/product/productHandler_test.go, productImport/product/productHeader.go, productImport/product/productModels.go, productImport/productImportHandler.go, productImport/reports/failuresReportBuilder.go, productImport/reports/reportHeader_test.go, productImport/reports/reportsHandler.go, productImport/reports/reportsHandler_test.go, productImport/reports/successReportBuilder.go
Map collumns from map config file should be used for result report
=> TSAPPS-238 Apply custom mapping to reports

offerImport/importHandler/importOffersToTradeshift.go, offerImport/offerImportHandler.go
Log messages changings according client request
=> TSAPPS-197, TSAPPS-230 Fix log messages

config/configModels/configModels.go, config/configModels/rawCommonConfigModel.go, file/converter.go, prepareImport/prepareImportHandler.go, prepareImport/xlsxSheetToCSVConverter.go, service.default.yaml
Bug was fixed: ugly and invalid config parameter name
=> TSAPPS-252 Rename config parameter

offerImport/importHandler/importOffersToTradeshift.go, offerImport/importHandler/offerActions.go, offerImport/importHandler/offerModel.go, offerImport/importHandler/offerModel_test.go, offerImport/offerReader/offerReader.go
When we impot offers, we check-does offer exists
If it it so, we should update it (if it is needed)
or norify that ofer exists already with the same data and we skip it
=> TSAPPS-280 Update  existened offer

productImport/reports/reportHeader_test.go, productImport/reports/successReportBuilder.go, productImport/reports/successReportHeader.go
If attribute has value in column UoM, summary report should contain column <Attribute_name>_UOM with UoM value
=> TSAPPS-284 Add UoM Columns to Sucess Report

adapters/csvH/adapter.go, file/converter.go
Add processing for cases:
- XLSX sheet has empty data/ has no valid rows: we skip sheet
- csv file is empty: we skip file and output error
- csv file has no valid rows: sip file and output error
=> TSAPPS-297 Process empty sheet data

offerImport/offerImportHandler.go, offerItemImport/offerITemImportHandler.go, productImport/productImportHandler.go, productImport/tradeshiftImportHandler/importProductsHandler.go
Hard to define by logs what kind of import stage is running now.
Added  clarification for each stage
=> TSAPPS-296 Clarify messages for imports
